### ISSUE TITLE
The meaning of the UUID tag

### ISSUE THREAD

**Issue by acnebs** [guillaumekh/iTMS-Tags-Remover#1]
Apple devices such as iPhones and iPads all have a UUID, or Universally Unique IDentifier, which is, as should be obvious, unique to each device. 

I would assume that the UUID tag indicates the UUID of the device on which the file itself was purchased.

**Comment by guillaumekh** [comment]
Possible but it seems like a bit of a stretch.
* The device's UUID is called the `UDID` in Apple parlance. The generic `UUID` can designate the unique identifier of pretty much anything.
* This wasn't always true but Apple now restricts access to the UDID for privacy and security reasons. It feels strange they would write it to the file metadata.

Ideally an in order to verify that, we would have a file that actually has the flag set, and the device used for purchase..
